 # install.packages("xlsx", dependencies = TRUE)  
 # install.packages("rjson")
  library("tools")
  library("foreign")
  library("xlsx")
  library("rjson")
  source("identify.R")
  source("file_types.R")
  source("read.R")
