#install.packages("xlsx", dependencies = TRUE)  
#sinstall.packages("rjson")
library("tools")
library("foreign")
#library("xlsx")
library("rjson")
library("purrr")
source("identify.R")
source("file_types.R")
source("read.R")
source("process.R")
